server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

grpc:
  client:
    user-service:
      address: 'static://localhost:50051'
      negotiation-type: plaintext
  server:
    port: 9090
    security:
      enabled: false