// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disnote/user/v1/user.proto

// Protobuf Java Version: 3.25.3
package com.disnote.grpc.user.v1;

public interface GetUserProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:disnote.user.v1.GetUserProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
