// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disnote/user/v1/user.proto

// Protobuf Java Version: 3.25.3
package com.disnote.grpc.user.v1;

public interface GetUserProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:disnote.user.v1.GetUserProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string full_name = 1 [json_name = "fullName"];</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 1 [json_name = "fullName"];</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
