// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disnote/user/v1/user.proto

// Protobuf Java Version: 3.25.3
package com.disnote.grpc.user.v1;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_disnote_user_v1_GetUserProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_disnote_user_v1_GetUserProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_disnote_user_v1_GetUserProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_disnote_user_v1_GetUserProfileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032disnote/user/v1/user.proto\022\017disnote.us" +
      "er.v1\"0\n\025GetUserProfileRequest\022\027\n\007user_i" +
      "d\030\001 \001(\tR\006userId\"5\n\026GetUserProfileRespons" +
      "e\022\033\n\tfull_name\030\001 \001(\tR\010fullName2p\n\013UserSe" +
      "rvice\022a\n\016GetUserProfile\022&.disnote.user.v" +
      "1.GetUserProfileRequest\032\'.disnote.user.v" +
      "1.GetUserProfileResponseB\'\n\030com.disnote." +
      "grpc.user.v1B\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_disnote_user_v1_GetUserProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_disnote_user_v1_GetUserProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_disnote_user_v1_GetUserProfileRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_disnote_user_v1_GetUserProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_disnote_user_v1_GetUserProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_disnote_user_v1_GetUserProfileResponse_descriptor,
        new java.lang.String[] { "FullName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
